default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  username: <%= ENV["DATABASE_USER_NAME"] %>
  password: <%= ENV["DATABASE_USER_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  host: localhost
  database: <%= ENV["DATABASE_NAME"] %>_<%= Jets.env %>

test:
  <<: *default
  host: localhost
  database: <%= ENV["DATABASE_NAME"] %>_<%= Jets.env %>

production:
  <<: *default
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  database: <%= ENV["DATABASE_NAME"] %>_<%= Jets.env %>